packages:
  - .

overrides:
  tailwindcss>nanoid: 3.3.7
  fast-xml-parser: 5.11.0
  path-to-regexp: 0.1.13
  lodash: 4.18.1
  lodash-es: 4.18.1

patchedDependencies:
  wouter@3.7.1: patches/wouter@3.7.1.patch
